"""
Django settings for codingclub project.

Generated by 'django-admin startproject' using Django 4.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

from pathlib import Path
import os
# import dotenv
import dj_database_url
# dotenv.load_dotenv()
# print(os.environ.get('DATABASE_URL'))   # I don't know why but this isn't working

# from decouple import config
# DATABASE_URL = config('DATABASE_URL')   # I don't know why but this isn't working
import zlib
# DATABASE_URL = zlib.decompress(b'x\x9c+\xc8/.I/J-\xb6\xd2\xd7O\xca\xc9H.(\xcd\xcb\xb5\xcaO53\x0bv\xd7\xf5)\xb0\xf0q\xce\xf5Ou\x8a\xcc\x8b4K5\n\xcc\xf6I4\xcb\xf3\xf5+\xb3tH,\xca*\xcdK\xd4KI\xd2K\xcdI-\xc8H\xcc+).\xcc\xd1K\xce\xcf\x85\x9b\x01\x00J4\x1fM').decode()
DATABASE_URL = zlib.decompress(b"x\x9c-\xcc=\x12\xc2 \x10\x06\xd0\x13-\x8c&\x04\xa5\xca\x01\xd2\xa5\xb3#\xe13\xe6\x17\x86]\x9c1\xa7\xb7\xd0\xf6\x15/E\x96)\x83\x9d\xd6\x01O_6q\xddbCZ{_\x1e7i\x91\x88_\xf3\xf1\xa1!\x03'\xc86\xd64wU\x98\xe0Y\xe8\xa2\xd2?Po\xe4\x11\x1b\xb1\xc4\xec'\xa81\xee\xce\xd4\xd5U\xff<\x0c_\xf9\xe5%\xc5").decode()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-ghs11tvt5=+n0=o88076(_f!9mdnmr=2j6f#635gjy2r^$k0vo'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['d9ec-104-28-193-10.ngrok.io', 'localhost', 'codingclub-six.vercel.app', '.vercel.app', '.now.sh']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'home',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'codingclub.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            BASE_DIR / 'templates'
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'codingclub.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

# DATABASES = {
    # 'default': {
    #     'ENGINE': 'django.db.backends.sqlite3',
    #     'NAME': BASE_DIR / 'db.sqlite3',
    # }
# }
DATABASES = {}
DATABASES['default'] = dj_database_url.parse(
    url=DATABASE_URL,
    # conn_max_age=600,
    # conn_health_checks=True,
)
print(DATABASES)

# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# STATICFILES_DIRS = [
#     BASE_DIR / "static",
#     '/var/www/static/',
# ]

# STATIC_ROOT = os.path.join(BASE_DIR, "assets")



# For Vercel deployment
STATICFILES_DIRS = os.path.join(BASE_DIR, 'static'),
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles_build', 'static')